# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: itce-courseware

steps:
# - script: dotnet test EchoServiceTests/EchoServiceTests.csproj --logger trx
#   displayName: Run unit tests
# - task: PublishTestResults@2
#   condition: succeededOrFailed()
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '**/*.trx'
- script: dotnet build EchoService/SimpleEcho.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build and push
  inputs:
    command: buildAndPush
    repository: andreyitce/itce-devops-cw
    containerRegistry: DockerHub
    Dockerfile: Dockerfile  

